### ISSUE TITLE
Generate unique Line colors for each skill

### ISSUE THREAD

**Issue by trevordavis** [awerchniak/viz_osrs#7]
We currently have a hard-coded skill color in hexadecimal in each Line object (see getLines() in GraphContainer).

It would be great to generate these values. However, we don't necessarily want to generate random values since they could be ugly or difficult to see colors. Instead, I recommend hard coding a list of valid line colors (one for each skill), then when a line is created, it picks from an available color. If we want to make it even easier, we could hardcode a Line color for each skill (see JavaScript's map object).

**Comment by awerchniak** [comment]
Fixed in 8c5210f5a50517f8a4034809f81396c84d39cd4c
